spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## REST CLIENT -> http://localhost:4004/api/service-requests
        ## API GATEWAY -> http://request-service:4000/service-requests
        - id: request-service-route
          uri: ${REQUEST_SERVICE_URL:http://request-service:4000}
          predicates:
            - Path=/api/service-requests/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ## REST CLIENT -> http://localhost:4004/auth/login
        ## API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://auth-service:4005}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ## REST CLIENT -> http://localhost:4004/api-docs/requests
        ## API GATEWAY -> http://request-service:4000/v3/api-docs
        - id: api-docs-request-route
          uri: ${REQUEST_SERVICE_URL:http://request-service:4000}
          predicates:
            - Path=/api-docs/requests
          filters:
            - RewritePath=/api-docs/requests,/v3/api-docs

        ## REST CLIENT -> http://localhost:4004/api-docs/auth
        ## API GATEWAY -> http://auth-service:4005/v3/api-docs
        - id: api-docs-auth-route
          uri: ${AUTH_SERVICE_URL:http://auth-service:4005}
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:4005}

server:
  port: 4004
